---
# The dataset and model paths. Should change according to device, there should be more than one dataset path
datasets-path: 
  - '...'


feature-extractor : '...'
e2e-model : '...' 
last-model : '...'


# Enviroment variables
train : True # True for generating training samples -  False for testing models
save-sample : True # True for saving samples in training 
num-trials : 1 # Number of trials (both training and testing)
num-tools : 3 # Number of tools in environment [1-6]
task : 'reach' # possible tasks ['reach', 'lift', 'minigolf']
dataset-path : "..." # the main folder of dataset

# Feature Extractor Parameters
num-points : 2000

# Model parameters
train-model : "e2e" 

# True for score based sequential tool selection
continue-solve : True

# Secondary Randomization
secondary-rand : True 

# Real end-to-end model
e2e-epoch : 60
e2e-batch : 32
e2e-normalize: True
e2e-lr: 0.0008 